# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.Category'),
        ),
    ]
