# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-12-10 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0021_auto_20191210_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_lower', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.Language')),
            ],
            options={
                'verbose_name': 'размер (перевод)',
                'verbose_name_plural': 'размер (перевод)',
            },
        ),
        migrations.RemoveField(
            model_name='size',
            name='vend_size',
        ),
        migrations.AddField(
            model_name='vendsize',
            name='izi_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Size'),
        ),
        migrations.AddField(
            model_name='translationsize',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='product_app.Size'),
        ),
    ]
