# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-12-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0022_auto_20191211_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
