# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-12-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0023_size_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='translationsize',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
